service: personal-cron

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 25
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  iamRoleStatements: # TODO: if this becomes used a lot, restrict roles per function or rename any relevant infrastructure to be cron-* prefixed
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - arn:aws:sns:*:*:*
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:lambda:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":function:personal-cron-*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:dynamodb:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":table/*"

package:
  individually: false
  include:
    - '!./**'
    - './**.py'
  exclude:
    - '**'

functions:
  kiva:
    handler: kiva_checker/main.main
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - schedule: rate(10 days)
    environment:
      SNS_TOPIC_ARN: arn:aws:sns:us-east-1:174225498255:KivaNotifier
      ISO_CODES: BD,BT,BZ,CA,GU,LA,NA,SS,TR,VI,ZA

  slack_keyword_rank:
    handler: slack_keyword_rank/main.lambda_handler
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    timeout: 60
    environment:
      # query_requests: '[{"query": "schedule message", "apps": ["AK7KWDFU3"]}, {"query": "recurring message", "apps": ["AK7KWDFU3"]}]'
      SHEETY_URL: ${env:SHEETY_URL}
      SHEETY_BEARER_TOKEN: ${env:SHEETY_BEARER_TOKEN}
    events:
      - schedule: 
          rate: rate(3 days)
          input:
            action: cron
            send_notification: true

custom:
  pythonRequirements:
    layer: true
  prune:
    automatic: true
    includeLayers: true
    number: 3

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-prune-plugin
